language: ruby
sudo: false
rvm:
  - 2.3.4
  - 2.4.1

env:
  global:
    - DATABASE_URL=postgres://postgres@localhost:5432/moorkit
    - REDIS_URL=redis://localhost:637
    - MK_RESQUE_CREDS="travis:travis"
    - RAILS_ENV=test
    - SECRET_KEY_BASE=secret_key
    - RUBY_ENV=test
  matrix:
    - DB=postgresql

before_install:
  - gem install bundler -v 1.12.5

cache:
  bundler: true

before_script:
  - make db-travis

services:
  - postgresql

addons:
  postgresql: "9.4"
  code_climate:
    repo_token: 26640320ccf0d4039ee13fe4c51d514f0907efa46431a836bfbeb4be7424cfa3
