default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['MK_PG_URL'] %>

development:
  <<: *default

test: &test
  <<: *default

production:
  <<: *default

cucumber:
  <<: *test
