default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DATABASE_CONNECTIONS", 5) %>
  url: <%= ENV.fetch("DATABASE_URL") %>

development:
  <<: *default

test: &test
  <<: *default

production:
  <<: *default

cucumber:
  <<: *test
