# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb83cf3293887f0dd123df7c212e125b30c90adc0f10b04d5e764a89d775aee47e5cc03b23e1cd8944a604069bb9f0b651ab5e7151177c6dcb4984c562de949f

test:
  secret_key_base: 77aeda0b424ac74ba9fed783efec8f7d57048aed541c41b3ce2ba7d72d98c1250630d5a435eaa654909c8dc083c41e458ecb33c91a2c51af2c0b1db885dd20c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
